name:                aoc2025
version:             0.1.0.0
github:              "githubuser/aoc2025"
license:             MIT
author:              "Milan Boers"
maintainer:          "mail@milanboers.nl"
copyright:           "2025 Milan Boers"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc2025#readme>

dependencies:
- base >= 4.7 && < 5
- split
- containers
- megaparsec
- matrix
- search-algorithms
- dijkstra-simple
- uglymemo
- random

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  aoc2025-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2025
